[WIP] circleci and github actions ci implementation
18F/newrelic-terraform pull request #8
Opened 2020-07-16 21:29 UTC by JJediny

Changes approach to only use declared terraform and referencing terraformer for refrerencing imported resources only

2020-07-22 21:47 UTC, afeld requested changes
General feedback:

- We were going to worry about continuous deployment separately/later—https://github.com/18F/tts-tech-portfolio/issues/631 is still in the Icebox. Since I don't think the CircleCI configuration will work as it stands, please delete it for now.
- What are all the `snapshot/` files? Do we still need them?

2020-07-22 21:47 UTC, afeld commented on .circleci/config.yml
> +            fi
If we end up having to repeat this config in a bunch of places, might make sense to [create an orb](https://circleci.com/docs/2.0/orb-intro/) for it (later).

2020-07-22 21:47 UTC, afeld commented on .circleci/config.yml
> +      - image: hashicorp/terraform:0.11.14
Is this version correct?

2020-07-22 21:47 UTC, afeld commented on .circleci/config.yml
> +          command: pytest tests
Assuming this was copied in? I think you can delete all of `validate`.

2020-07-22 21:47 UTC, afeld commented on README.md
> +To protect agaisnt committing credentials or other secrets:
You were right before 😉

2020-07-22 21:47 UTC, afeld commented on README.md
>  - [Mozilla's Secrets OPerationS (SOPS)](https://github.com/mozilla/sops)
Is SOPS actually being used for this repository? If not, let's remove from the README to reduce confusion.

2020-10-19 15:57 UTC, its-a-lisa-at-work commented
What is the current status of this pull request? @afeld do you still want the changes made by @JJediny ?

2020-10-19 23:03 UTC, afeld commented
@JJediny If you think you can get the feedback addressed in under, say, an hour, I say just go for it and we can get this merged. Otherwise, let's close and it can be reopened later.

2020-10-21 16:36 UTC, closed without merging